import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {readState,writeState,DEFAULTS,filterJobs,pqeRange,discoverySignal,safeURL,publicCSV,daysOld,validateSnapshot} from '../web/core.mjs';
const job=(id,patch={})=>({id:id.padStart(24,'0'),title:'Legal Counsel',company:'Example Company',location:'London',region:'london',workMode:'unspecified',url:'https://example.com/jobs/'+id,sources:['inhouse'],sourceKind:'employer-feed',firstSeen:null,sourceLastSeen:'2026-09-16T07:00:00Z',descriptionCheckedAt:null,status:'listed',snapshotNew:false,practice:'general',pqe:null,pqeEvidence:null,seniority:'unspecified',warnings:[],duplicateGroup:null,linkRepaired:false,...patch});
const jobs=[job('1',{title:'IP Counsel',practice:'ip',snapshotNew:true}),job('2',{title:'Commercial Solicitor',practice:'commercial',region:'rest',location:'Manchester',snapshotNew:true}),job('3',{title:'Senior IP Associate',practice:'ip',seniority:'senior-title',pqe:'6+ PQE'}),job('4',{location:'2 Locations',region:'unknown'}),job('5',{status:'missing'}),job('6',{title:'Serious Injury Solicitor',practice:'other',pqe:'NQ'}),job('7',{title:'Corporate Counsel',practice:'corporate',pqe:'2-4 PQE'})];
const select=patch=>filterJobs(jobs,{...DEFAULTS,view:'discover',...patch});
test('New AND London filters combine',()=>assert.deepEqual(select({fresh:'1',region:'london'}).map(j=>j.id),[jobs[0].id]));
test('new listings never leak into a different location filter',()=>assert.deepEqual(select({fresh:'1',region:'rest'}).map(j=>j.id),[jobs[1].id]));
test('unknown locations excluded from UK filter',()=>assert.ok(!select({region:'uk'}).includes(jobs[3])));
test('unknown locations remain discoverable explicitly',()=>assert.deepEqual(select({region:'unknown'}),[jobs[3]]));
test('archive is not mixed into live snapshot results',()=>assert.ok(!select({region:'all'}).includes(jobs[4])));
test('archive is available without implying confirmed closure',()=>assert.deepEqual(select({view:'archive'}),[jobs[4]]));
test('Today is limited to listings new in the latest snapshot',()=>assert.deepEqual(select({view:'today',region:'all'}).map(j=>j.id),[jobs[0].id,jobs[1].id]));
test('Discover preserves other practice areas',()=>assert.ok(select({view:'discover'}).includes(jobs[5])));
test('search ANDs words and supports exclusion',()=>assert.deepEqual(select({q:'IP -senior'}),[jobs[0]]));
test('quoted phrases are supported',()=>assert.deepEqual(select({q:'"Commercial Solicitor"'}),[jobs[1]]));
test('PQE regex handles NQ and ranges',()=>{assert.deepEqual(pqeRange('NQ – 2 PQE'),[0,2]);assert.deepEqual(pqeRange('2–4 PQE'),[2,4]);assert.equal(pqeRange(null),null);});
test('stated NQ filter does not infer Associate as junior',()=>assert.ok(!select({pqe:'nq'}).includes(jobs[2])));
test('PQE range overlap is explicit',()=>assert.ok(select({pqe:'early'}).includes(jobs[6])));
test('unknown PQE filter excludes extracted evidence',()=>assert.ok(!select({pqe:'unknown'}).includes(jobs[6])));
test('private hidden status excluded from public discovery view',()=>assert.ok(!filterJobs(jobs,{...DEFAULTS,view:'discover'},{[jobs[0].id]:{status:'hidden'}}).includes(jobs[0])));
test('private saved view requires an actual saved status',()=>assert.deepEqual(filterJobs(jobs,{...DEFAULTS,view:'saved'},{[jobs[0].id]:{status:'saved'}}),[jobs[0]]));
test('opening has no effect on applications',()=>assert.deepEqual(filterJobs(jobs,{...DEFAULTS,view:'applications'},{}),[]));
test('applied roles excluded from Today but retained in tracker',()=>{const local={[jobs[0].id]:{status:'applied'}};assert.ok(!filterJobs(jobs,DEFAULTS,local).includes(jobs[0]));assert.deepEqual(filterJobs(jobs,{...DEFAULTS,view:'applications'},local),[jobs[0]]);});
test('deep-link state round-trips',()=>{const s={...DEFAULTS,view:'discover',region:'london',q:'"IP counsel" -senior',fresh:'1',source:'boards',page:3};assert.deepEqual(readState(writeState(s)),s);});
test('malformed deep links sanitise enums and pagination',()=>{const s=readState('#view=evil&region=bad&page=-1&source=%3Cscript%3E');assert.equal(s.view,'today');assert.equal(s.region,'uk');assert.equal(s.page,1);assert.equal(readState('#view=today').region,'all');assert.equal(readState('#view=discover').region,'uk');});
test('private state is never serialised into URLs',()=>assert.ok(!writeState({...DEFAULTS,note:'secret',passphrase:'secret'}).includes('secret')));
test('unsafe URLs rejected',()=>{for(const url of ['javascript:alert(1)','data:text/html,bad','/internal','https://u:p@example.com'])assert.equal(safeURL(url),null);});
test('CSV excludes private notes and neutralises formulas',()=>{const csv=publicCSV([job('a',{company:'=HYPERLINK("evil")',note:'SECRET NOTE'})]);assert.ok(!csv.includes('SECRET NOTE'));assert.ok(csv.includes("'=HYPERLINK"));});
test('null dates do not become fresh',()=>assert.equal(daysOld(null),null));
test('publication date not used to infer observation age',()=>assert.equal(daysOld('2026-01-01T00:00:00Z',Date.parse('2026-01-10T00:00:00Z')),9));
test('wrong practice area cannot outrank an IP discovery',()=>assert.ok(discoverySignal(jobs[5])<discoverySignal(jobs[0])));
test('public snapshot validates and has no candidate/private fields',()=>{const d=validateSnapshot(JSON.parse(fs.readFileSync(new URL('../data/jobs.json',import.meta.url))));for(const j of d.jobs)for(const key of ['notes','candidate','profile','applied','applicationStatus'])assert.ok(!(key in j));});
test('production snapshot new-and-London regression',()=>{const d=JSON.parse(fs.readFileSync(new URL('../data/jobs.json',import.meta.url)));const matching=filterJobs(d.jobs,{...DEFAULTS,view:'discover',fresh:'1',region:'london'});assert.ok(matching.every(j=>j.snapshotNew&&j.region==='london'));});
test('malformed payload rejects duplicate IDs',()=>assert.throws(()=>validateSnapshot({schemaVersion:1,jobs:[jobs[0],jobs[0]],sources:[]})));
