import test from 'node:test';import assert from 'node:assert/strict';import {Vault} from '../web/vault.mjs';
const PASS='correct horse battery stable';const ID='000000000000000000000001';
class Store{constructor(){this.m=new Map();}getItem(k){return this.m.get(k)??null;}setItem(k,v){this.m.set(k,v);}}
test('workspace is ciphertext at rest, unlocks correctly, and forgets key on lock',async()=>{const s=new Store(),v=new Vault(s);await v.create(PASS);await v.update(ID,{status:'applied',note:'PRIVATE_SENTINEL_中文',nextAction:'Follow up'});const raw=v.export();assert.ok(!raw.includes('PRIVATE_SENTINEL'));assert.ok(!raw.includes(PASS));assert.ok(!raw.includes('applied'));v.lock();assert.equal(v.data,null);assert.equal(v.key,null);await v.unlock(PASS);assert.equal(v.data.jobs[ID].note,'PRIVATE_SENTINEL_中文');assert.equal(v.data.jobs[ID].history[0].status,'applied');});
test('wrong password never replaces data',async()=>{const v=new Vault(new Store());await v.create(PASS);const before=v.export();v.lock();await assert.rejects(()=>v.unlock('wrong passphrase'));assert.equal(v.export(),before);assert.equal(v.unlocked,false);});
test('every encryption uses a new IV',async()=>{const v=new Vault(new Store());await v.create(PASS);const iv=JSON.parse(v.export()).iv;await v.update(ID,{status:'saved'});assert.notEqual(JSON.parse(v.export()).iv,iv);});
test('restore validates decryption before replacing existing workspace',async()=>{const a=new Vault(new Store()),b=new Vault(new Store());await a.create(PASS);await a.update(ID,{note:'backup note'});await b.create('another good passphrase');const before=b.export();await assert.rejects(()=>b.restore(a.export(),'wrong'));assert.equal(b.export(),before);await b.restore(a.export(),PASS);assert.equal(b.data.jobs[ID].note,'backup note');});
test('locked workspace refuses mutation',async()=>{const v=new Vault(new Store());await assert.rejects(()=>v.update(ID,{status:'saved'}));});
test('short passphrases rejected',async()=>{const v=new Vault(new Store());await assert.rejects(()=>v.create('short'));assert.equal(v.exists,false);});
test('rapid mutations are serialised without losing records',async()=>{const v=new Vault(new Store());await v.create(PASS);await Promise.all([v.update(ID,{status:'saved'}),v.update(ID,{note:'second write'})]);v.lock();await v.unlock(PASS);assert.equal(v.data.jobs[ID].status,'saved');assert.equal(v.data.jobs[ID].note,'second write');});
test('stale tab cannot overwrite newer encrypted data',async()=>{const s=new Store(),a=new Vault(s),b=new Vault(s);await a.create(PASS);await b.unlock(PASS);await a.update(ID,{note:'newest'});await assert.rejects(()=>b.update(ID,{note:'stale'}));await b.unlock(PASS);assert.equal(b.data.jobs[ID].note,'newest');});
test('corrupt and unsupported backups rejected',async()=>{const v=new Vault(new Store());await assert.rejects(()=>v.restore('{"format":"other"}',PASS));assert.equal(v.exists,false);});
test('prototype pollution IDs rejected',async()=>{const v=new Vault(new Store());await v.create(PASS);await assert.rejects(()=>v.update('__proto__',{status:'saved'}));});
test('storage failures do not leave a falsely successful unlocked vault',async()=>{const v=new Vault({getItem(){return null;},setItem(){throw new Error('Quota exceeded');}});await assert.rejects(()=>v.create(PASS));assert.equal(v.unlocked,false);});
test('saved searches are inside the encrypted envelope',async()=>{const v=new Vault(new Store());await v.create(PASS);await v.saveSearch('PRIVATE SEARCH','#view=discover&q=patents');assert.ok(!v.export().includes('PRIVATE SEARCH'));await v.unlock(PASS);assert.equal(v.data.searches[0].name,'PRIVATE SEARCH');});
test('saved search and job mutation do not race',async()=>{const v=new Vault(new Store());await v.create(PASS);await Promise.all([v.update(ID,{note:'retain note'}),v.saveSearch('retain search','#q=counsel')]);v.lock();await v.unlock(PASS);assert.equal(v.data.jobs[ID].note,'retain note');assert.equal(v.data.searches[0].name,'retain search');});
